In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x


array([1, 2, 3])

In [3]:
y = np.array([4,5,6])

In [4]:
y

array([4, 5, 6])

In [5]:
m = np.array([[7,8,9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
m.shape

(2, 3)

In [8]:
n = np.arange(0, 30, 2)

In [9]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
n = n.reshape(3,5)

In [11]:
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [12]:
o = np.linspace(0, 4, 9)

In [13]:
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [15]:
o.reshape(3,3)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [16]:
np.ones(3,2)

TypeError: data type not understood

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [20]:
y

array([4, 5, 6])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
p = np.ones([2,3], int)

In [25]:
p


array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [29]:
x + y

array([5, 7, 9])

In [30]:
x

array([1, 2, 3])

In [31]:
y

array([4, 5, 6])

In [32]:
x**2

array([1, 4, 9])

In [33]:
x

array([1, 2, 3])

In [34]:
y

array([4, 5, 6])

In [35]:
x.dot(y)

32

In [36]:
z = np.array([y, y**2])

In [37]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [38]:
z.shape

(2, 3)

In [39]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [40]:
z.T.shape

(3, 2)

In [41]:
z.dtype

dtype('int64')

In [43]:
z = z.astype('f')

In [44]:
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [45]:
a = np.array([-4, -2, 1, 3, 5])

In [49]:
a.sum()

3

In [50]:
a.mean()

0.6

In [51]:
a.max()

5

In [52]:
a.min()

-4

In [53]:
a.std()

3.2619012860600183

In [54]:
a.argmax()

4

In [55]:
a.argmin()

0

In [56]:
s = np.arange(13)**2

In [57]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [58]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [59]:
s[1:5]

array([ 1,  4,  9, 16])

In [60]:
s[-4:]

array([ 81, 100, 121, 144])

In [61]:
r = np.arange(36)

In [62]:
r.resize((6,6))

In [63]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
r[2,2]

14

In [65]:
r[3, 3:6]

array([21, 22, 23])

In [66]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [67]:
r[-1, ::2]

array([30, 32, 34])

In [68]:
r[r>30]

array([31, 32, 33, 34, 35])

In [69]:
r[r>30] = 30

In [70]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [71]:
r2 = r[:3, :3]

In [72]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [76]:
r2[:] = 0

In [77]:
r

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [75]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
test = np.random.randint(0, 10, (4,3))
test

array([[3, 7, 2],
       [6, 2, 3],
       [7, 7, 6],
       [5, 6, 5]])

In [80]:
for row in test:
    print(row)

[3 7 2]
[6 2 3]
[7 7 6]
[5 6 5]


In [82]:
for i in range(len(test)):
    print(test[i])

[3 7 2]
[6 2 3]
[7 7 6]
[5 6 5]


In [83]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [3 7 2]
row 1 is [6 2 3]
row 2 is [7 7 6]
row 3 is [5 6 5]


In [84]:
test2 = test**2

In [85]:
test2

array([[ 9, 49,  4],
       [36,  4,  9],
       [49, 49, 36],
       [25, 36, 25]])

In [86]:
test

array([[3, 7, 2],
       [6, 2, 3],
       [7, 7, 6],
       [5, 6, 5]])

In [89]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[3 7 2] + [ 9 49  4] = [12 56  6]
[6 2 3] + [36  4  9] = [42  6 12]
[7 7 6] + [49 49 36] = [56 56 42]
[5 6 5] + [25 36 25] = [30 42 30]
